name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge minor/patch updates
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Check PR title
        id: check
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"(minor"* ]] || \
             [[ "${{ github.event.pull_request.title }}" == *"(patch"* ]]; then
            echo "safe=true" >> $GITHUB_OUTPUT
          else
            echo "safe=false" >> $GITHUB_OUTPUT
          fi

      - name: Enable auto-merge
        if: steps.check.outputs.safe == 'true'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}