version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 10
    reviewers:
      - "ivan629"
    assignees:
      - "ivan629"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Auto-merge minor/patch, manual review major
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all development dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Group all production dependencies
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Bucharest"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "ivan629"
    insecure-external-code-execution: "deny"