name: Bug Report
description: Report a bug in DagEngine
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce
      placeholder: |
        1. Install @dagengine/core
        2. Run code...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: DagEngine version
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      options:
        - 20.x
        - 22.x
        - 24.x
    validations:
      required: true